### PR TITLE
ecdsa-jcs-2019 algorithms

### PR DESCRIPTION
**Pull request by PatStLouis**
As discussed in our last meeting, here is the ecdsa-jcs-2019 algorithm file.

### CODE REVIEW

**Review by BigBlueHat — APPROVED** [review]
Thanks, @PatStLouis

**Review by gannan08 — CHANGES_REQUESTED** [review]
**1. I don't see where we test this [Create Proof](https://www.w3.org/TR/vc-di-ecdsa/#create-proof-ecdsa-jcs-2019)**

> If `unsecuredDocument.@context` is present, set `proof.@context` to `unsecuredDocument.@context`.

During create proof, a compliant cryptosuite should be adding a context to the proof.

**2. Nor this [Verify Proof](https://www.w3.org/TR/vc-di-ecdsa/#verify-proof-ecdsa-jcs-2019)**

> If `proofOptions.@context` exists:
> Check that the `securedDocument.@context` starts with all values contained in the `proofOptions.@context` in the same order. Otherwise, set verified to false and skip to the last step.
> Set `unsecuredDocument.@context` equal to `proofOptions.@context`.

During verify proof, a compliant cryptosuite should be matching the context on the secured document with the context on the proof if `proofOptions.@context` exists.

**Comment by PatStLouis** [comment]
@gannan08 thanks for the review, I can add two tests for the highlighted sections, however I want to point out that they don't contain normative statements.

In the Data Model for proof representation:

> The type property MUST be DataIntegrityProof.
>
> The cryptosuite property MUST be ecdsa-rdfc-2019, ecdsa-jcs-2019, or ecdsa-sd-2023.
>
> The value of the proofValue property is produced according to the cryptosuite type and is specified in either Section [3.2.1 Create Proof (ecdsa-rdfc-2019)](https://www.w3.org/TR/vc-di-ecdsa/#create-proof-ecdsa-rdfc-2019), or Section [3.3.1 Create Proof (ecdsa-jcs-2019)](https://www.w3.org/TR/vc-di-ecdsa/#create-proof-ecdsa-jcs-2019), or Section [3.6.1 Create Base Proof (ecdsa-sd-2023)](https://www.w3.org/TR/vc-di-ecdsa/#create-base-proof-ecdsa-sd-2023), or Section [3.6.6 Add Derived Proof (ecdsa-sd-2023)](https://www.w3.org/TR/vc-di-ecdsa/#add-derived-proof-ecdsa-sd-2023).

The later doesn't have any normative statements. Would you suggest to change the text to:
> The value of the proofValue property MUST be produced according to ...

I'm trying to be pragmatic about limiting test cases for normative statements only. Happy to make an exception if there's a specific statement we need tested which isn't normative.

**Comment by PatStLouis** [comment]
I also want to point out that the vectors for jcs doesn't have context in the proof:
[](https://www.w3.org/TR/vc-di-ecdsa/#example-signed-credential-1)

Implementations I've seen also omit this. I will raise an issue on the spec about this.

**Comment by PatStLouis** [comment]
Discussed this further, I will add missing tests.

**Pull request merged**
